#!/bin/sh

###
 # This file is subject to the terms and conditions defined in file LICENSE,
 # which is part of this source code package.
 #
 # See the NOTICE file distributed with this work for additional
 # information regarding copyright ownership.
###

if [ "$1" = "0" ]
then
  rm -rf /var/lib/phenotips/
fi
