#!/bin/sh

###
 # This file is subject to the terms and conditions defined in file LICENSE,
 # which is part of this source code package.
 #
 # See the NOTICE file distributed with this work for additional
 # information regarding copyright ownership.
###

set -e

# Stop Tomcat
if [[ -a /usr/lib/systemd/system/tomcat.service ]]
then
  /bin/systemctl stop tomcat.service
fi
